# NUMPY-4

In [2]:
import numpy as np

##### Matrix indexleri

In [3]:
myList = [[10,20,30],[20,30,40],[40,50,60]]

In [4]:
myMatrix = np.array(myList)

In [5]:
myMatrix

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

In [6]:
myMatrix[0]

array([10, 20, 30])

In [11]:
myMatrix[0][1] #matrix dizisi veri çekme

20

In [12]:
myMatrix[1][1]

30

In [14]:
myMatrix[1,1] #[1][1] ile aynı anlamda

30

In [16]:
myMatrix[1:,2] #x'i index numarası 1ve 2 olan değerleri aldık ve sonra so değeri çağırdık

array([40, 60])

In [18]:
myMatrix #yukarda bahsedilen şey 40 60 sonra 2 satırın son 2 sütunu

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

## operations

In [21]:
newArr = np.random.randint(1,100,20)

In [22]:
newArr

array([29, 64, 98, 29, 20, 29, 16, 41, 83, 75, 32, 64, 97, 87,  8, 70, 59,
       33, 71, 87])

In [23]:
newArr > 24 #24 den büyük elemanları boolen döndürür

array([ True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True])

In [24]:
sonuc = newArr > 24

In [25]:
sonuc

array([ True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True])

In [27]:
newArr[sonuc] #24den büyük sayıları listeledi sadece

array([29, 64, 98, 29, 29, 41, 83, 75, 32, 64, 97, 87, 70, 59, 33, 71, 87])

In [28]:
newArr + newArr

array([ 58, 128, 196,  58,  40,  58,  32,  82, 166, 150,  64, 128, 194,
       174,  16, 140, 118,  66, 142, 174])

In [29]:
newArr - newArr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [30]:
newArr * newArr

array([ 841, 4096, 9604,  841,  400,  841,  256, 1681, 6889, 5625, 1024,
       4096, 9409, 7569,   64, 4900, 3481, 1089, 5041, 7569])

In [32]:
np.sqrt(newArr) #karekök

array([5.38516481, 8.        , 9.89949494, 5.38516481, 4.47213595,
       5.38516481, 4.        , 6.40312424, 9.11043358, 8.66025404,
       5.65685425, 8.        , 9.8488578 , 9.32737905, 2.82842712,
       8.36660027, 7.68114575, 5.74456265, 8.42614977, 9.32737905])

In [33]:
np.max(newArr)

98

In [34]:
np.min(newArr)

8