## Numpy: Bilimsel matematik hesaplarini hizli yapmamizi saglayan bir kutuphanedir

####  Numpy dizileri, Python dizilerindeki gibidir fakat daha hizli calisir. Ayrıca python listelerinden farklı olarak Numpy dizileri homojen yapıda olmalıdır yani dizi içindeki tüm elemanlar aynı veri tipinden olmalıdır.

In [10]:
import numpy as np

# numpy ve python array farklarini daha rahat gorelim
python_array = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
numpy_array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# ayrica dilersek bir python array np array e donusturulebilir
np_arrayDonusturme = np.array(python_array) 


print(python_array)
print(type(python_array))

print(numpy_array)
print(type(numpy_array))

print(np_arrayDonusturme)
print(type(np_arrayDonusturme))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'list'>
[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [14]:
# matrix olusturma
matrix_listesi = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix_listesi)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Metodlar

##  .ndim : dizi boyutunu verir

In [24]:
# dizilerin kac boyutlu oldugunu bulalim
matrix_listesi = np.array([[1,2,3],[4,5,6],[7,8,9]])
numpy_array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

print('matrix_listesi "{}" boyutludur'.format(matrix_listesi.ndim))
print('numpy_array "{}" boyutludur'.format(numpy_array.ndim))

matrix_listesi "2" boyutludur
numpy_array "1" boyutludur


## shape :  satir ve sutun sayisi bulma  x.shape(SATIR,SUTUN)  Not! : tek boyutlu dizi de sadece 1 deger bulunur

In [55]:
# shape ile matrixlerin satir ve sutun sayilarini gorelim
matrix_listesi = np.array([[1,2,3],[4,5,6],[7,8,9]])
numpy_array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

print(matrix_listesi.shape)
print(numpy_array.shape)

(3, 3)
(10,)


## reshape : matrisi yeniden boyutlandirir  x.reshape(SATIR,SUTUN) 

In [56]:
# orijinal hallerini yazalim
matrix_listesi = np.array([[1,2,3],[4,5,6],[7,8,9]])
numpy_array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

print('matrix listesi orijinal \n{}'.format(matrix_listesi))
print('\nnumpy listesi orijinal \n{}'.format(numpy_array))

# reshape ile degistirelim
matrix_listesi = matrix_listesi.reshape(1,9)
numpy_array = numpy_array.reshape(5,2)

print('\nreshape edilmis matrix listesi \n{}'.format(matrix_listesi))
print('\nreshape edilmis numpy listesi \n{}'.format(numpy_array))

matrix listesi orijinal 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

numpy listesi orijinal 
[0 1 2 3 4 5 6 7 8 9]

reshape edilmis matrix listesi 
[[1 2 3 4 5 6 7 8 9]]

reshape edilmis numpy listesi 
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


##### Not! : reshape ederken eleman sayisina gore ediyoruz. 10 elemanli matrisi (3,2) seklinde yazdirmazsin (5,2) (2,5) (1,10) (10,1) seklinde olabilir

## arange() ve linspace() 
#### DIKKAT !!  Bu iki method birbirine benzer
####  ARANGE() range ifadesi gibi belli sayidan belli sayiya kadar belirli adim kadar ilerler
#### LINSPACE() ise belirli sayilar arasinda esit aralikli kac sayi uretilecegini cikarir

In [67]:
# arange() kullanimi
# sifirdan 10 a 2'ser artarak gitsin
print(np.arange(0,10,2))

# 0 dan 2 ye kadar 5er artaraka git
print(np.arange(0,2,5))

[0 2 4 6 8]
[0]


In [69]:
# linspace() kullanimi
# 0-10 arasi esit aralikli 2 sayi getirsin
print(np.linspace(0,10,2))

# 0-2 arasi esit aralikli 5 sayi getir
print(np.linspace(0,2,5))

[ 0. 10.]
[0.  0.5 1.  1.5 2. ]


## eye() birim matrix

In [72]:
# 10x10 luk birim matrix
np.eye(10) 

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## zeros() ve ones()

In [77]:
# gerekli durumlarda 0 ve 1lerden lusan matrislere ihtiyac olabilir
print(np.zeros([5,5]))
print('\n')
print(np.ones([4,3]))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## random : rastele sayi uretme || linspace aksine araliklar esit olmaz

In [85]:
import random

print(np.random.randn(4,4))
print(np.random.randint(0,2,20))

[[-0.46995456  0.05316895 -0.24382212  0.61165771]
 [ 1.05235314 -0.38475386  0.1862537  -1.06857838]
 [-0.82378781  0.61871828 -1.36337953  0.14947778]
 [-1.80854617 -0.7916108  -1.11326078  0.07857906]]
[0 1 1 0 0 0 0 1 0 0 1 1 1 1 1 0 0 0 1 1]


## concatenate([matris1, matris2], axis = 0/1)  matrix birlestirme

In [94]:
# diziyi 2 boyutlu yapalim ve kendi ile birlestirelim
numpy_array = np.array([0,1, 2, 3, 4, 5, 6, 7, 8, 9])
numpy_array = numpy_array.reshape([5,2])

# satir bazli birlestirme islemi
print(np.concatenate([numpy_array, numpy_array], axis = 0))
print('\n')

# sutun bazli birlestirme islemi 
print(np.concatenate([numpy_array, numpy_array], axis = 1))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]
 [0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


[[0 1 0 1]
 [2 3 2 3]
 [4 5 4 5]
 [6 7 6 7]
 [8 9 8 9]]


## matris eleman secme islemleri [satir][sutun]

In [121]:
matrix_listesi = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix_listesi)
print('\n')

# ilk satirin son elemani
print(matrix_listesi[0,2])
print('\n')

# tum satirlarin 2. elemani
print(matrix_listesi[:,1])
print('\n')

# 1. ve 3. satiri getir
print(matrix_listesi[[0,2]])
print('\n')


# tersten yazdirma
print(matrix_listesi[::-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


3


[2 5 8]


[[1 2 3]
 [7 8 9]]


[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [119]:
# tek boyutlu matriste birkac ornek var
numpy_array = np.array([0,1, 2, 3, 4, 5, 6, 7, 8, 9])
print(numpy_array)

# 2 den 5 e kadar olan degerlere 0 ata
numpy_array[2:6] = 0
print(numpy_array)

#ters cevir
print(numpy_array[::-1]) 

[0 1 2 3 4 5 6 7 8 9]
[0 1 0 0 0 0 6 7 8 9]
[9 8 7 6 0 0 0 0 1 0]


## Matematiksel islemler

### sum(), max() ve min()

In [125]:
# toplam
matrix_listesi = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix_listesi.sum())

# dizideki max deger
print(matrix_listesi.max())

# dizideki min deger
print(matrix_listesi.min())

45
9
1


### mean() : ortalama
### median() : ortanca deger
### var() : varyans
### std() : standart sapma

In [137]:
numpy_array = np.array([0 ,1, 2, 3, 4, 5, 6, 7, 8, 9])

# ortalama
print(numpy_array.mean())

# ortanca deger(medyan)
print(np.median(numpy_array))

# varyans
print(matrix_listesi.var())

# standart sapma
print(matrix_listesi.std())

4.5
4.5
6.666666666666667
2.581988897471611


## matrisler ile matematiksel islemler

In [146]:
numpy_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
numpy_array = numpy_array.reshape(3,3)
print(numpy_array)
print('\n')

# iki matrisi toplama
print(numpy_array + numpy_array)
print('\n')

# iki matrisi cikarma
print(numpy_array - numpy_array)
print('\n')

# iki matrisi carpma
print(numpy_array * numpy_array)
print('\n')

# iki matrisi bolme
print(numpy_array / numpy_array)
print('\n')

# matrisiteki her elemani 5 ile toplama
print(numpy_array + 5)
print('\n')

# matrisiteki her elemani 5 ile carpma
print(numpy_array * 5)
print('\n')

# matrisiteki her elemanin karekoku
print(np.sqrt(numpy_array))
print('\n')

# matrisin transpozu
print('Transpoz hali\n {}'.format(numpy_array.T))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


[[0 0 0]
 [0 0 0]
 [0 0 0]]


[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


Transpoz hali
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


## Kosullu ifadeler

In [154]:
# if else kullanmadan rahatlikla islemler yapilabilir
numpy_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# 5ten buyuk olan degerleri
boolen_array = numpy_array > 5
print(boolen_array)
print(numpy_array[boolen_array])
print('\n')

# 5ten kucuk elemanlari
print(numpy_array < 5)
print(numpy_array[numpy_array < 5])

[False False False False False  True  True  True  True]
[6 7 8 9]


[ True  True  True  True False False False False False]
[1 2 3 4]
