#  NUMPY-2

## random

In [1]:
import numpy as np

In [3]:
np.random.randn(8) #random bir numpy dizisi döndürüyor

array([-1.42842805,  0.52391824,  1.39088636,  0.55904374, -0.10488495,
        1.64504222,  0.68891047, -1.16993229])

In [4]:
np.random.randn(8,3)

array([[-1.10246958, -1.99195174,  0.08175919],
       [-0.99153145,  0.20349402,  1.03761079],
       [-0.59436443, -1.05444104,  0.83680178],
       [ 1.86094356, -2.48281371,  0.28789622],
       [-0.56001149,  0.71456696,  0.03088312],
       [-0.56162368,  0.0103079 ,  1.29507681],
       [-0.14621992, -1.00999359,  1.11292083],
       [ 0.18077488,  0.7611318 , -1.58804692]])

In [7]:
np.random.randint(1,10) #rastgele int sayı döndürüyor

9

In [9]:
np.random.randint(1,10,5) #son değer kaç rakam istediğimiz

array([2, 3, 6, 8, 6])

In [12]:
myNumpyArr = np.arange(15)

In [13]:
myNumpyArr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
myRandomArr = np.random.randint(0,40,5)

In [15]:
myRandomArr

array([21, 35, 12, 25, 13])

#### "_arange_" sıralı bir şekilde sayılar üretirken "_randint_" rastgele sayılar üretir(int). "_randn_" ise rastgele randint gibi rastgele sayılar üretir(float). Bu belirtilen fonksiyonların hepsi "_np.random_"un modülleridir

# NUMPY ARRAY METHODS

In [23]:
myNumpyArr.reshape(5,3) #verilen diziyi matris yapma

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

Burada dikkat edilmesi gereken şey girilen değer çarpımı dizideki eleman sayısına eşit olmalı

In [24]:
myNumpyArr.max() #dizi içindeki en yüksek değer

14

In [28]:
myRandomArr.min() #min değer

12

In [31]:
myRandomArr.argmax() #en yüksek değerin dizi içindeki yeri

1

In [33]:
myRandomArr.argmin() #en düşük değerin dizi içindeki yeri

2

In [37]:
myNumpyArr.shape #dizi içindeki değerler

(15,)

In [40]:
newNumpyArr = myNumpyArr.reshape(5,3) #2d diziyi değişkene atadık

In [41]:
newNumpyArr.shape #yeni değişkenin shape değeri

(5, 3)