# NUMPY-3

In [1]:
import numpy as np

In [2]:
myArr = np.arange(0,15)

In [4]:
myArr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
myArr[5]

5

In [6]:
myArr[3:5]

array([3, 4])

In [9]:
myArr[3:8] = -5 #aradaki değerleri değiştirdik

In [10]:
myArr

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [11]:
otherArr = np.arange(0,24)

In [12]:
otherArr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [15]:
slicingArr = otherArr[4:9] #other dizisindeki belirtilen aralık değerleri diğer diziye yazıldı

In [16]:
slicingArr

array([4, 5, 6, 7, 8])

In [19]:
slicingArr[:] = 0 #dizi içindeki tüm değerleri değiştirdik

In [20]:
slicingArr

array([0, 0, 0, 0, 0])

In [23]:
otherArr #slicing dizinde değişim yapmama rağmen değişiklik other dizisine de etki etmiş

array([ 0,  1,  2,  3,  0,  0,  0,  0,  0,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

**********************************
Peki bu durumu nasıl düzelteceğiz??

In [24]:
exArr = np.arange(0,24)

In [26]:
exArr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [27]:
exArrCopy = exArr.copy() #exArr dizisini exArrCopy'ye kopyaladık

In [28]:
exArr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [34]:
exArrCopySlicing = exArrCopy[3:6] #kopya diziyi yeni bir diziye atadık 

In [35]:
exArrCopySlicing[:] = 800

In [39]:
exArrCopySlicing #slicing dizinde değişti

array([800, 800, 800])

In [40]:
exArrCopy #kopya dizide değerleri değiştirdik 

array([  0,   1,   2, 800, 800, 800,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [41]:
exArr #main dizide değerler değişmedi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

#### Dizi değerlerini değiştirmek için ekstra 2 diziye ve "_copy()_" kopyasına ihtiyacımız var